### ISSUE TITLE
Commands fail with OSError randomly

### ISSUE THREAD

**Issue by chbndrhnns** [timothycrosley/cruft#18]
If I run `cruft check` or `cruft update`, it fails randomly. I'll attach the two error message that appear.

To me it seems related with cleanup of temporary directories.

Python: 3.7.6
OS: OS X

<details>
<summary>Error 1</summary>

```bash
(cc) ➜  awesome-poitras-brinxrxh cruft check
Traceback (most recent call last):
  File "/Users/powerjo/.local/share/virtualenvs/cc-mqLroxNX/bin/cruft", line 8, in <module>
    sys.exit(__hug__.cli())
  File "/Users/powerjo/.local/share/virtualenvs/cc-mqLroxNX/lib/python3.7/site-packages/hug/api.py", line 441, in __call__
    result = self.commands.get(command)()
  File "/Users/powerjo/.local/share/virtualenvs/cc-mqLroxNX/lib/python3.7/site-packages/hug/interface.py", line 649, in __call__
    raise exception
  File "/Users/powerjo/.local/share/virtualenvs/cc-mqLroxNX/lib/python3.7/site-packages/hug/interface.py", line 645, in __call__
    result = self.output(self.interface(**pass_to_function), context)
  File "/Users/powerjo/.local/share/virtualenvs/cc-mqLroxNX/lib/python3.7/site-packages/hug/interface.py", line 129, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "/Users/powerjo/.local/share/virtualenvs/cc-mqLroxNX/lib/python3.7/site-packages/cruft/api.py", line 102, in check
    return True
  File "/Users/powerjo/.local/share/virtualenvs/cc-mqLroxNX/lib/python3.7/tempfile.py", line 807, in __exit__
    self.cleanup()
  File "/Users/powerjo/.local/share/virtualenvs/cc-mqLroxNX/lib/python3.7/tempfile.py", line 811, in cleanup
    _shutil.rmtree(self.name)
  File "/Users/powerjo/.local/share/virtualenvs/cc-mqLroxNX/lib/python3.7/shutil.py", line 494, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/Users/powerjo/.local/share/virtualenvs/cc-mqLroxNX/lib/python3.7/shutil.py", line 436, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/Users/powerjo/.local/share/virtualenvs/cc-mqLroxNX/lib/python3.7/shutil.py", line 434, in _rmtree_safe_fd
    os.rmdir(entry.name, dir_fd=topfd)
OSError: [Errno 66] Directory not empty: '.git'
```
</details>

<details>
<summary>Error 2</summary>

```bash
(cc) ➜  awesome-poitras-brinxrxh cruft check
Traceback (most recent call last):
  File "/Users/powerjo/.local/share/virtualenvs/cc-mqLroxNX/bin/cruft", line 8, in <module>
    sys.exit(__hug__.cli())
  File "/Users/powerjo/.local/share/virtualenvs/cc-mqLroxNX/lib/python3.7/site-packages/hug/api.py", line 441, in __call__
    result = self.commands.get(command)()
  File "/Users/powerjo/.local/share/virtualenvs/cc-mqLroxNX/lib/python3.7/site-packages/hug/interface.py", line 649, in __call__
    raise exception
  File "/Users/powerjo/.local/share/virtualenvs/cc-mqLroxNX/lib/python3.7/site-packages/hug/interface.py", line 645, in __call__
    result = self.output(self.interface(**pass_to_function), context)
  File "/Users/powerjo/.local/share/virtualenvs/cc-mqLroxNX/lib/python3.7/site-packages/hug/interface.py", line 129, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "/Users/powerjo/.local/share/virtualenvs/cc-mqLroxNX/lib/python3.7/site-packages/cruft/api.py", line 102, in check
    return True
  File "/Users/powerjo/.local/share/virtualenvs/cc-mqLroxNX/lib/python3.7/tempfile.py", line 807, in __exit__
    self.cleanup()
  File "/Users/powerjo/.local/share/virtualenvs/cc-mqLroxNX/lib/python3.7/tempfile.py", line 811, in cleanup
    _shutil.rmtree(self.name)
  File "/Users/powerjo/.local/share/virtualenvs/cc-mqLroxNX/lib/python3.7/shutil.py", line 494, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/Users/powerjo/.local/share/virtualenvs/cc-mqLroxNX/lib/python3.7/shutil.py", line 432, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/Users/powerjo/.local/share/virtualenvs/cc-mqLroxNX/lib/python3.7/shutil.py", line 452, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/Users/powerjo/.local/share/virtualenvs/cc-mqLroxNX/lib/python3.7/shutil.py", line 450, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: '35774.tags'
```

</details>

**Comment by chbndrhnns** [comment]
Seems to me like a known problem with `shutil.rmtree`:

https://bugs.python.org/issue33240
https://github.com/python/cpython/pull/13580
