### ISSUE TITLE
Improve cruft update's rejection fallback

### ISSUE THREAD

**Issue by samj1912** [timothycrosley/cruft#49]
Currently, if a user modifies a cookiecutter template's file in a manner that it is no longer similar to the original version, cruft update fails to apply the patch using git 3 way merge and instead falls back to git apply --reject, which produces a bunch of*.rej files. This is not the best way for an end user to manually fix updates. We should look into how we can improve this experience. For more details about the fallback, see #47 and #48

**Comment by nickderobertis** [comment]
I agree there is room for improvement, I just recently upgraded cruft and have been trying to figure out a good workflow with .rej files but so far to no avail. 

For my usage, I am always using a git repo, and I like how cruft < 1.4 created merge conflict markers in the files because there are lots of GUIs for handling these, and IMO more straightforward when the original and changes are in the same file. I would just delete all the .orig files (they are not particularly useful when everything is tracked in git) and resolve the conflicts.

According to #35 cruft went to using `git apply` over `patch` to handle renames and deletes which is certainly an improvement. But I feel that it took a step backwards in terms of user experience in updates for git repos. 

I did a quick experiment, where cruft falls back to the patch behavior `patch -p1 --merge` only for the rejections (as `git apply --reject` is being used right now).  This seems to reproduce the original behavior but I have not tested whether it still properly handles renames and deletes. It seems logical it would still be working for git repos since it tries `git apply -3` first. Perhaps only for git repos we could enable fallback to `patch` and still use `git apply --reject` for non-git, but that does have the downside of different UX for git vs. non-git. I noticed also adding the `--no-backup-if-mismatch` flag will prevent it from creating the .orig files, which would be the ideal workflow for me. 

One strategy I'm thinking which could may resolve this and give the same UX across git and non git would be:

| Project Type      | First Pass | Second Pass |
| ----------- | ----------- | ---------- |
| Git      | `git apply -3`   | `patch -p1 --merge --no-backup-if-mismatch` |
| Non-git   | `git apply --reject` | `patch -p1 --merge` |

I'm curious your thoughts on this approach. I'm also curious whether you would consider having command line options in the library to customize this behavior, e.g. adding a flag for `--no-backup-if-mismatch`, or perhaps even giving the user control to override specific commands which are being used. 

I'm happy to experiment more with this and submit a PR depending on what you would consider should be included in cruft.

**Comment by tekumara** [comment]
I like the workflow you've suggested @nickderobertis and would use it over the current workflow.

**Comment by samj1912** [comment]
The above looks good to me. The only thing to consider is the behavior of patch in Linux vs macOS. IIRC macOS doesn't have the gnu version by default and it would be nice if we could vendor it.

**Comment by mikeoconnor0308** [comment]
Any update on this? The user experience of conflicts is the main pain point in my use of cruft.

**Comment by Woile** [comment]
I'm having the same issue. In my case, it has to replace a single line a `Makefile` and this error appears.
Anyone knows how could I prevent this and how to fix it?

**Comment by jonzarecki** [comment]
@samj1912 what does a non-git project type mean?
Are there any tests present for 3-way merge creating a merge conflict instead of a .rej file?

**Comment by sharadpattanshetti** [comment]
Hi I am having similar issue hence wanted to know if this solution will address it. 
When I introduce a new injected cookiecutter variables in my template then the update fails saying certain attribute is not found. Below is the error: 
`Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\cookiecutter\generate.py", line 352, in generate_files
    generate_file(
  .........
    raise rewrite_traceback_stack(source=source)
  File ".\template.yaml", line 20, in top-level template code
    variable1: '2588237'
jinja2.exceptions.UndefinedError: 'collections.OrderedDict object' has no attribute 'variable1'`

**Comment by sharadpattanshetti** [comment]
Hi,
Any update on this? For newly added cookie cutter fields, the cruft update fails.

**Comment by gaspardc-met** [comment]
Hey,
Are there any updates on this issue ? 

Here I am, still using `cruft < 1.4` in 2025 to handle merge conflicts and not have to dig through .rej files. 
AM I the only one ?

**Comment by jszopi** [comment]
# My understanding

`git apply -3` will ~only work~ work best if the `upstream-template-old` hash is known to git. This will only happen if at some point you checked in the file verbatim. If any hunks don't apply cleanly, you'll get git conflicts -- good, you know how to handle these. But this is where your luck runs out. Once you resolve the conflicts and check in the result, its hash won't be that of `upstream-template-new`. The next time you're pulling updates, `git apply -3` will ~fail~ only have the diff context to go off of. This time, if any hunks don't apply cleanly, it will not produce git conflicts, it will do nothing and exit with a failure code.

This is where `cruft` falls back onto `git apply --reject`. If any hunks don't apply cleanly, a `.rej` file will be created containing the whole diff. This can be superfluous, because it will include any hunks that were already applied. Personally, the first time I saw these, I was trying to `git apply` them, hoping for a git conflict, but instead I got:

```
error: patch fragment without header at line 2
```

I only learned to reach for `patch` from this Issue. It does a great job of applying the `.rej` file to the original. It's a no-op for any hunks that had already been applied and it surrounds conflicts with markers. As it's not a git conflict and I couldn't figure out how to make git treat it as such, I couldn't use `meld` on it. VSCode did offer the in-line conflict resolution, but it didn't engage the "3-way merge editor" (`patch` supports the `diff3` format).

Anyway, the volume of conflicts in a cookiecutter context should be manageable to be edited by hand. If `cruft` was to print a message "run `patch`, results not guaranteed", I think it would already be an improvement.

# Second pass proposal

@nickderobertis and @Cadair proposed that `cruft` runs `patch` as a fallback in case `git apply -3` fails. I'm not sure about this. As git isn't aware of the conflicts, the feedback the user gets about the conflicts is different than in the `git apply -3` case. git isn't there to stop the user accidentally committing the file with conflict markers unresolved.

Also, `patch` won't always work. I have two scenarios where it fails:

<details>
<summary><code>patch</code> creates incorrect conflicts</summary>

Start with a commit behind the `HEAD` of the demo repo:

```console
$ cruft create -c 3958ca2ed0cad4d65c15912f6ab714720eb528a1 https://github.com/timothycrosley/cookiecutter-python/
```

If at this point you `git init` and commit, `upstream-template-old` will be known to git and used by `git apply -3`. Otherwise, you'll fall back onto `git apply --reject`.

Make the following change:

```diff
diff --git a/scripts/lint.sh b/scripts/lint.sh
index 5b8ac0f..934610a 100755
--- a/scripts/lint.sh
+++ b/scripts/lint.sh
@@ -2,9 +2,3 @@
 set -euxo pipefail

 poetry run cruft check
-poetry run mypy --ignore-missing-imports python_project_name/
-poetry run isort --check --diff python_project_name/ tests/
-poetry run black --check python_project_name/ tests/
-poetry run flake8 python_project_name/ tests/
-poetry run safety check -i 39462
-poetry run bandit -r python_project_name/
```

and run `cruft update`. With `git apply -3`, you'll get the following git conflict:

```diff
diff --cc scripts/lint.sh
index 934610a,07aa5f3..0000000
--- a/scripts/lint.sh
+++ b/scripts/lint.sh
@@@ -2,3 -2,9 +2,19 @@@
  set -euxo pipefail

  poetry run cruft check
++<<<<<<< ours
++||||||| base
++poetry run mypy --ignore-missing-imports python_project_name/
++poetry run isort --check --diff python_project_name/ tests/
++poetry run black --check python_project_name/ tests/
++poetry run flake8 python_project_name/ tests/
++poetry run safety check -i 39462
++poetry run bandit -r python_project_name/
++=======
+ poetry run mypy --ignore-missing-imports python_project_name/
+ poetry run isort --check --diff python_project_name/ tests/
+ poetry run black --check python_project_name/ tests/
+ poetry run flake8 python_project_name/ tests/
+ poetry run safety check -i 39462 -i 40291
+ poetry run bandit -r python_project_name/
++>>>>>>> theirs
```

but with the `git apply --reject` fallback followed by `patch --merge=diff3`, you'll get:

```diff
diff --git a/scripts/lint.sh b/scripts/lint.sh
index 934610a..aa1168f 100755
--- a/scripts/lint.sh
+++ b/scripts/lint.sh
@@ -1,4 +1,18 @@
 #!/bin/bash
 set -euxo pipefail

+<<<<<<<
 poetry run cruft check
+|||||||
+poetry run isort --check --diff python_project_name/ tests/
+poetry run black --check python_project_name/ tests/
+poetry run flake8 python_project_name/ tests/
+poetry run safety check -i 39462
+poetry run bandit -r python_project_name/
+=======
+poetry run isort --check --diff python_project_name/ tests/
+poetry run black --check python_project_name/ tests/
+poetry run flake8 python_project_name/ tests/
+poetry run safety check -i 39462 -i 40291
+poetry run bandit -r python_project_name/
+>>>>>>>
```

Note that the `poetry run cruft check` line is only present in the `ours` branch, so if you wanted to converge with the upstream by selecting `theirs`, the result would be incorrect.

</details>

<details>
<summary><code>patch</code> can fail to apply a <code>.rej</code> file</summary>

```console
$ git init .
$ git branch -m upstream
$ echo "A\nB\nC" > foo.txt
$ git add foo.txt
$ git commit -m "ABC"
$ echo "D\nE\nF" >> foo.txt
$ git add foo.txt
$ git commit -m "ABCDEF"
$ # This is a similar command to that in cruft's `_git_diff`:
$ git --no-pager -c diff.noprefix= diff --relative --binary --src-prefix=upstream-template-old/ --dst-prefix=upstream-template-new/ HEAD~1 HEAD > upstream.diff
$ cat upstream.diff
diff --git upstream-template-old/foo.txt upstream-template-new/foo.txt
index b1e6722..cead32e 100644
--- upstream-template-old/foo.txt
+++ upstream-template-new/foo.txt
@@ -1,3 +1,6 @@
 A
 B
 C
+D
+E
+F
$ git switch -c downstream HEAD~1
$ touch blank.txt && mv blank.txt foo.txt
$ git add foo.txt
$ git commit -m "Blank"
$ # What a three-way merge can do when it knows the upstream-template-old
$ git apply -3 upstream.diff
Applied patch to 'foo.txt' with conflicts.
U foo.txt
$ cat foo.txt
<<<<<<< ours
||||||| base
A
B
C
=======
A
B
C
D
E
F
>>>>>>> theirs
$ # Undo the changes from the three-way merge
$ git restore --staged foo.txt && git restore foo.txt
$ # What patch can do:
$ git apply --reject upstream.diff
Checking patch foo.txt...
error: while searching for:
A
B
C

error: patch failed: foo.txt:1
Applying patch foo.txt with 1 reject...
Rejected hunk #1.
$ cat foo.txt.rej
diff a/foo.txt b/foo.txt        (rejected hunks)
@@ -1,3 +1,6 @@
 A
 B
 C
+D
+E
+F
$ patch foo.txt foo.txt.rej
patching file foo.txt
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file foo.txt.rej
$ cat foo.txt.rej
--- /dev/null
+++ /dev/null
@@ -1,3 +1,6 @@
 A
 B
 C
+D
+E
+F
$ cat foo.txt
$ # File is still blank
```

</details>

# Summary

When `git apply -3` doesn't apply cleanly but is able to find the `upstream-template-old`, it creates git conflicts. git gives obvious feedback about what needs to be fixed. This is in contrast to a fallback onto `patch`, which adds conflict markers that aren't recognized by git. (If anyone knows a way to tell git there are conflicts, let me know).

The proposal to fallback onto `patch` call can also result in incorrect conflicts or fail to apply. `copier` [is said](https://github.com/cruft/cruft/issues/181#issuecomment-1506887857) to use `git merge-file` in place of `patch` -- I'm curious if the results are as good as those of `git apply -3` if it were given the `upstream-template-old`.

# My proposal

My preference would be to look for ways to make a three-way merge work by giving git access to the full history of the upstream, rather than just the diff between two commits. I think #267 is on the right track but I haven't thought an implementation through yet. Will we need merge commits with the upstream template, which mustn't be squashed? Or store the incremental resolutions from `git rerere` inside the repo?

**Comment by yolave** [comment]
any updates on this? It would be really helpful to have a better approach to handle conflicts when applying any updates. I'll be glad to help with the solution and push this feature forward.

**Comment by alainsanguinetti** [comment]
Just to add that I find it surprising that when using "view" option the changes look ok and are successfully applied, and afterwards when saying "y", to apply what I just saw, I get rejections though
